### PR TITLE
Add Transcribe support

### PR DESCRIPTION
**Pull request by danarbaugh**
This adds support for all 8 resource types within [the Transcribe AWS service](https://docs.aws.amazon.com/transcribe/latest/dg/what-is.html).

## Testing

The following test script can be used to create one of each resource type:

```bash
#!/bin/bash
set -ex

# Generate a random string to use as a bucket name and classifier name suffix
RANDOM_STRING=$(openssl rand -hex 20)
# Generate a random string for shorter names
SHORT_RANDOM_STRING=$(openssl rand -hex 10)

# Set your preferred bucket names
INPUT_BUCKET="input-bucket-$RANDOM_STRING"
OUTPUT_BUCKET="output-bucket-$RANDOM_STRING"

# Get AWS account ID
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
echo "AWS Account ID: $AWS_ACCOUNT_ID"

# Create input bucket
aws s3api create-bucket --bucket $INPUT_BUCKET
echo "Input bucket created: s3://$INPUT_BUCKET"

# Create output bucket
aws s3api create-bucket --bucket $OUTPUT_BUCKET
echo "Output bucket created: s3://$OUTPUT_BUCKET"

# Create IAM Role for Comprehend access
ROLE_NAME="transcribe-access-role-$RANDOM_STRING"
aws iam create-role \
  --role-name $ROLE_NAME \
  --assume-role-policy-document '{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Principal": {
          "Service": "transcribe.amazonaws.com"
        },
        "Action": "sts:AssumeRole"
      }
    ]
  }'

# Attach AmazonS3FullAccess managed policy to IAM role (for demo purposes)
aws iam attach-role-policy \
  --role-name $ROLE_NAME \
  --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess

echo 'Waiting 30 seconds for IAM role to propagate...'
sleep 30

cat <<EOF > test-category.json
{
  "CategoryName": "test-category-$SHORT_RANDOM_STRING",
  "InputType": "POST_CALL",
  "Rules": [
    {
      "InterruptionFilter": {
        "AbsoluteTimeRange": {
          "First": 60000
        },
        "Negate": false,
        "ParticipantRole": "CUSTOMER",
        "Threshold": 10000
      }
    },
    {
      "NonTalkTimeFilter": {
        "Negate": false,
        "RelativeTimeRange": {
          "EndPercentage": 80,
          "StartPercentage": 10
        },
        "Threshold": 20000
      }
    },
    {
      "SentimentFilter": {
        "ParticipantRole": "AGENT",
        "Sentiments": [
          "NEGATIVE"
        ]
      }
    },
    {
      "TranscriptFilter": {
        "Negate": true,
        "AbsoluteTimeRange": {
          "First": 10000
        },
        "Targets": [
          "welcome",
          "hello"
        ],
        "TranscriptFilterType": "EXACT"
      }
    }
  ]
}
EOF

# create call analytics category
aws transcribe create-call-analytics-category \
  --cli-input-json file://test-category.json

# start call analytics job
## get a sample wav to use
wget https://www2.cs.uic.edu/~i101/SoundFiles/preamble.wav
aws s3 cp preamble.wav s3://$INPUT_BUCKET/
## start the job
aws transcribe start-call-analytics-job \
  --call-analytics-job-name "test-job-$SHORT_RANDOM_STRING" \
  --media "MediaFileUri=s3://$INPUT_BUCKET/preamble.wav" \
  --data-access-role-arn arn:aws:iam::$AWS_ACCOUNT_ID:role/$ROLE_NAME \
  --channel-definitions ChannelId=0,ParticipantRole=AGENT ChannelId=1,ParticipantRole=CUSTOMER

# create a language model
## make placeholder training data in the input bucket
cat <<EOF > words.txt
The quick brown fox jumps over the lazy dog
EOF
aws s3 cp words.txt s3://$INPUT_BUCKET/my-clm-training-data/
aws s3 cp words.txt s3://$INPUT_BUCKET/my-clm-tuning-data/
## create the language model
aws transcribe create-language-model \
  --base-model-name NarrowBand \
  --model-name my-first-language-model \
  --input-data-config S3Uri=s3://$INPUT_BUCKET/my-clm-training-data/,TuningDataS3Uri=s3://$INPUT_BUCKET/my-clm-tuning-data/,DataAccessRoleArn=arn:aws:iam::$AWS_ACCOUNT_ID:role/$ROLE_NAME \
  --language-code en-US

# start medical transcription job
## get a sample sound file to use
wget https://www.hpisum.com/samples/ESL-Cardio-sample.wav
aws s3 cp ESL-Cardio-sample.wav s3://$INPUT_BUCKET/
## start the job
aws transcribe start-medical-transcription-job \
  --medical-transcription-job-name "test-med-job-$SHORT_RANDOM_STRING" \
  --language-code en-US \
  --media "MediaFileUri=s3://$INPUT_BUCKET/ESL-Cardio-sample.wav" \
  --output-bucket-name $OUTPUT_BUCKET \
  --specialty PRIMARYCARE \
  --type CONVERSATION

# create medical vocabulary
## create a text file with the vocabulary
cat <<EOF > my-medical-vocab.txt
Phrase,SoundsLike,IPA,DisplayAs
Los-Angeles,,l ɔ s æ n ʤ ə l ə s,Los Angeles
Eva-Maria,ay-va-ma-ree-ah,,
A.B.C.-s,ay-bee-sees,,ABCs
Amazon-dot-com,,,Amazon.com
C.L.I.,,s i ɛ l aɪ,CLI
Andorra-la-Vella,ann-do-rah-la-bay-ah,,Andorra la Vella
Dynamo-D.B.,,,DynamoDB
V.X.-zero-two,,,VX02
V.X.-zero-two-Q.,,,VX02Q
EOF
aws s3 cp my-medical-vocab.txt s3://$INPUT_BUCKET/
## create the vocabulary
aws transcribe create-medical-vocabulary \
  --vocabulary-name "test-med-vocab-$SHORT_RANDOM_STRING" \
  --language-code en-US \
  --vocabulary-file-uri "s3://$INPUT_BUCKET/my-medical-vocab.txt"

# start transcription job
aws transcribe start-transcription-job \
  --transcription-job-name "test-job-$SHORT_RANDOM_STRING" \
  --media "MediaFileUri=s3://$INPUT_BUCKET/preamble.wav" \
  --language-code en-US

# create a vocabulary
aws transcribe create-vocabulary \
  --vocabulary-name "test-vocab-$SHORT_RANDOM_STRING" \
  --language-code en-US \
  --phrases "hello" "world" "how are you"

# create a vocabulary filter
aws transcribe create-vocabulary-filter \
  --vocabulary-filter-name "test-vocab-filter-$SHORT_RANDOM_STRING" \
  --language-code en-US \
  --words "hello" "world" "how" "are" "you"
```

### CODE REVIEW

**Review by corybekk — COMMENTED** [review]
Hey Dan I ran aws-nuke after running the test script you added in `cl-tf-aws`. Below is the output of aws-nuke

It looks like it failed to delete the language model because the status of it is `in progress`. Would you happen to know how long those jobs run? and if we should be worried about cleaning them up once an account lease has expired?

```
Do you really want to nuke the account with the ID 299719426765 and the alias 'alias-299719426765'?
Waiting 3s before continuing.
us-east-1 - TranscribeCallAnalyticsJob - [CompletionTime: "2023-09-05T17:26:57Z", CreationTime: "2023-09-05T17:24:44Z", LanguageCode: "en-US", Name: "test-job-ac78d0e4993b628729d2", StartTime: "2023-09-05T17:24:44Z", Status: "COMPLETED"] - would remove
us-east-1 - TranscribeLanguageModel - [BaseModelName: "NarrowBand", CreateTime: "2023-09-05T17:24:48Z", LanguageCode: "en-US", LastModifiedTime: "2023-09-05T17:24:59Z", ModelStatus: "IN_PROGRESS", Name: "my-first-language-model1", UpgradeAvailability: "false"] - would remove
us-east-1 - TranscribeVocabulary - [LanguageCode: "en-US", LastModifiedTime: "2023-09-05T17:25:01Z", Name: "test-vocab-ac78d0e4993b628729d2", State: "FAILED"] - would remove
us-east-1 - TranscribeMedicalVocabulary - [LanguageCode: "en-US", LastModifiedTime: "2023-09-05T17:24:58Z", Name: "test-med-vocab-ac78d0e4993b628729d2", State: "FAILED"] - would remove
us-east-1 - TranscribeTranscriptionJob - [CompletionTime: "2023-09-05T17:25:24Z", CreationTime: "2023-09-05T17:24:59Z", LanguageCode: "en-US", Name: "test-job-ac78d0e4993b628729d2", StartTime: "2023-09-05T17:24:59Z", Status: "COMPLETED"] - would remove
us-east-1 - TranscribeMedicalTranscriptionJob - [CreationTime: "2023-09-05T17:24:55Z", FailureReason: "The audio sample rate 8000 Hz is not supported. Change the audio sample rate of your media file and try your request again.", InputType: "CONVERSATION", LanguageCode: "en-US", Name: "test-med-job-ac78d0e4993b628729d2", OutputLocationType: "CUSTOMER_BUCKET", Specialty: "PRIMARYCARE", StartTime: "2023-09-05T17:24:55Z", Status: "FAILED"] - would remove
us-east-1 - TranscribeVocabularyFilter - [LanguageCode: "en-US", LastModifiedTime: "2023-09-05T17:25:02Z", Name: "test-vocab-filter-ac78d0e4993b628729d2"] - would remove
us-east-1 - TranscribeCallAnalyticsCategory - [CreateTime: "2023-09-05T17:24:34Z", InputType: "POST_CALL", LastUpdateTime: "2023-09-05T17:24:34Z", Name: "test-category-ac78d0e4993b628729d2"] - would remove
Scan complete: 8 total, 8 nukeable, 0 filtered.

Do you really want to nuke these resources on the account with the ID 299719426765 and the alias 'alias-299719426765'?
Waiting 3s before continuing.
us-east-1 - TranscribeCallAnalyticsJob - [CompletionTime: "2023-09-05T17:26:57Z", CreationTime: "2023-09-05T17:24:44Z", LanguageCode: "en-US", Name: "test-job-ac78d0e4993b628729d2", StartTime: "2023-09-05T17:24:44Z", Status: "COMPLETED"] - triggered remove
us-east-1 - TranscribeLanguageModel - [BaseModelName: "NarrowBand", CreateTime: "2023-09-05T17:24:48Z", LanguageCode: "en-US", LastModifiedTime: "2023-09-05T17:24:59Z", ModelStatus: "IN_PROGRESS", Name: "my-first-language-model1", UpgradeAvailability: "false"] - failed
us-east-1 - TranscribeVocabulary - [LanguageCode: "en-US", LastModifiedTime: "2023-09-05T17:25:01Z", Name: "test-vocab-ac78d0e4993b628729d2", State: "FAILED"] - triggered remove
us-east-1 - TranscribeMedicalVocabulary - [LanguageCode: "en-US", LastModifiedTime: "2023-09-05T17:24:58Z", Name: "test-med-vocab-ac78d0e4993b628729d2", State: "FAILED"] - triggered remove
us-east-1 - TranscribeTranscriptionJob - [CompletionTime: "2023-09-05T17:25:24Z", CreationTime: "2023-09-05T17:24:59Z", LanguageCode: "en-US", Name: "test-job-ac78d0e4993b628729d2", StartTime: "2023-09-05T17:24:59Z", Status: "COMPLETED"] - triggered remove
us-east-1 - TranscribeMedicalTranscriptionJob - [CreationTime: "2023-09-05T17:24:55Z", FailureReason: "The audio sample rate 8000 Hz is not supported. Change the audio sample rate of your media file and try your request again.", InputType: "CONVERSATION", LanguageCode: "en-US", Name: "test-med-job-ac78d0e4993b628729d2", OutputLocationType: "CUSTOMER_BUCKET", Specialty: "PRIMARYCARE", StartTime: "2023-09-05T17:24:55Z", Status: "FAILED"] - triggered remove
us-east-1 - TranscribeVocabularyFilter - [LanguageCode: "en-US", LastModifiedTime: "2023-09-05T17:25:02Z", Name: "test-vocab-filter-ac78d0e4993b628729d2"] - triggered remove
us-east-1 - TranscribeCallAnalyticsCategory - [CreateTime: "2023-09-05T17:24:34Z", InputType: "POST_CALL", LastUpdateTime: "2023-09-05T17:24:34Z", Name: "test-category-ac78d0e4993b628729d2"] - triggered remove

Removal requested: 7 waiting, 1 failed, 0 skipped, 0 finished

us-east-1 - TranscribeCallAnalyticsJob - [CompletionTime: "2023-09-05T17:26:57Z", CreationTime: "2023-09-05T17:24:44Z", LanguageCode: "en-US", Name: "test-job-ac78d0e4993b628729d2", StartTime: "2023-09-05T17:24:44Z", Status: "COMPLETED"] - waiting
us-east-1 - TranscribeLanguageModel - [BaseModelName: "NarrowBand", CreateTime: "2023-09-05T17:24:48Z", LanguageCode: "en-US", LastModifiedTime: "2023-09-05T17:24:59Z", ModelStatus: "IN_PROGRESS", Name: "my-first-language-model1", UpgradeAvailability: "false"] - failed
us-east-1 - TranscribeVocabulary - [LanguageCode: "en-US", LastModifiedTime: "2023-09-05T17:25:01Z", Name: "test-vocab-ac78d0e4993b628729d2", State: "FAILED"] - waiting
us-east-1 - TranscribeMedicalVocabulary - [LanguageCode: "en-US", LastModifiedTime: "2023-09-05T17:24:58Z", Name: "test-med-vocab-ac78d0e4993b628729d2", State: "FAILED"] - waiting
us-east-1 - TranscribeTranscriptionJob - [CompletionTime: "2023-09-05T17:25:24Z", CreationTime: "2023-09-05T17:24:59Z", LanguageCode: "en-US", Name: "test-job-ac78d0e4993b628729d2", StartTime: "2023-09-05T17:24:59Z", Status: "COMPLETED"] - waiting
us-east-1 - TranscribeMedicalTranscriptionJob - [CreationTime: "2023-09-05T17:24:55Z", FailureReason: "The audio sample rate 8000 Hz is not supported. Change the audio sample rate of your media file and try your request again.", InputType: "CONVERSATION", LanguageCode: "en-US", Name: "test-med-job-ac78d0e4993b628729d2", OutputLocationType: "CUSTOMER_BUCKET", Specialty: "PRIMARYCARE", StartTime: "2023-09-05T17:24:55Z", Status: "FAILED"] - waiting
us-east-1 - TranscribeVocabularyFilter - [LanguageCode: "en-US", LastModifiedTime: "2023-09-05T17:25:02Z", Name: "test-vocab-filter-ac78d0e4993b628729d2"] - waiting
us-east-1 - TranscribeCallAnalyticsCategory - [CreateTime: "2023-09-05T17:24:34Z", InputType: "POST_CALL", LastUpdateTime: "2023-09-05T17:24:34Z", Name: "test-category-ac78d0e4993b628729d2"] - waiting

Removal requested: 7 waiting, 1 failed, 0 skipped, 0 finished

us-east-1 - TranscribeLanguageModel - [BaseModelName: "NarrowBand", CreateTime: "2023-09-05T17:24:48Z", LanguageCode: "en-US", LastModifiedTime: "2023-09-05T17:24:59Z", ModelStatus: "IN_PROGRESS", Name: "my-first-language-model1", UpgradeAvailability: "false"] - failed

```

**Comment by danarbaugh** [comment]
> It looks like it failed to delete the language model because the status of it is `in progress`. Would you happen to know how long those jobs run? and if we should be worried about cleaning them up once an account lease has expired?

Thank you for asking this. I thought these only took a few minutes, but after more thorough testing, it looks like they take about 30-50 min for the model to fully train. There is not a way to stop the model creation before issuing a delete command or any way to do a forced deletion with it in an `IN_PROGRESS` state. I will follow up with you on this...

**Review by corybekk — APPROVED** [review]

**Review by swhite-oreilly — CHANGES_REQUESTED** [review]
@danarbaugh all other resource types did successfully get removed except an IN_PROGRESS language model.

```
Removal requested: 0 waiting, 1 failed, 0 skipped, 15 finished

us-east-1 - TranscribeLanguageModel - [BaseModelName: "NarrowBand", CreateTime: "2023-09-06T14:29:00Z", LanguageCode: "en-US", LastModifiedTime: "2023-09-06T14:29:09Z", ModelStatus: "IN_PROGRESS", Name: "my-first-language-model-9f05901a7d6ab64ac886", UpgradeAvailability: "false"] - failed

Removal requested: 0 waiting, 1 failed, 0 skipped, 15 finished

us-east-1 - TranscribeLanguageModel - [BaseModelName: "NarrowBand", CreateTime: "2023-09-06T14:29:00Z", LanguageCode: "en-US", LastModifiedTime: "2023-09-06T14:29:09Z", ModelStatus: "IN_PROGRESS", Name: "my-first-language-model-9f05901a7d6ab64ac886", UpgradeAvailability: "false"] - failed

Removal requested: 0 waiting, 1 failed, 0 skipped, 15 finished

ERRO[0065] There are resources in failed state, but none are ready for deletion, anymore. 

us-east-1 - TranscribeLanguageModel - [BaseModelName: "NarrowBand", CreateTime: "2023-09-06T14:29:00Z", LanguageCode: "en-US", LastModifiedTime: "2023-09-06T14:29:09Z", ModelStatus: "IN_PROGRESS", Name: "my-first-language-model-9f05901a7d6ab64ac886", UpgradeAvailability: "false"] - failed
ERRO[0065] BadRequestException: The language model you are trying to delete is not in COMPLETED or FAILED status. Try you request again when the model is COMPLETED or FAILED. 
Error: failed
```

I think we need to add logic to stop an in progress model similar to how AWS Comprehend model jobs are handled and then remove.

**Comment by danarbaugh** [comment]
> I think we need to add logic to stop an in progress model similar to how AWS Comprehend model jobs are handled and then remove.

There's unfortunately no way to stop jobs in progress with any [Transcribe command](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/transcribe/) and the [delete-language-model command](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/transcribe/delete-language-model.html) does not support any type of force or stop parameter.

**Comment by swhite-oreilly** [comment]
> > I think we need to add logic to stop an in progress model similar to how AWS Comprehend model jobs are handled and then remove.
> 
> There's unfortunately no way to stop jobs in progress with any [Transcribe command](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/transcribe/index.html#cli-aws-transcribe) and the [delete-language-model command](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/transcribe/delete-language-model.html) does not support any type of force or stop parameter.

Per your slack thread I agree with your assessment.  Looks good.  
```
us-east-1 - TranscribeMedicalVocabulary - [LanguageCode: "en-US", LastModifiedTime: "2023-09-06T14:29:13Z", Name: "test-med-vocab-9f05901a7d6ab64ac886", State: "FAILED"] - removed
us-east-1 - TranscribeMedicalVocabulary - [LanguageCode: "en-US", LastModifiedTime: "2023-09-05T14:32:59Z", Name: "test-med-vocab-a3b39174b6ba8c8f18f9", State: "FAILED"] - removed
us-east-1 - TranscribeVocabulary - [LanguageCode: "en-US", LastModifiedTime: "2023-09-06T14:29:18Z", Name: "test-vocab-9f05901a7d6ab64ac886", State: "FAILED"] - removed
us-east-1 - TranscribeVocabulary - [LanguageCode: "en-US", LastModifiedTime: "2023-09-05T14:33:02Z", Name: "test-vocab-a3b39174b6ba8c8f18f9", State: "FAILED"] - removed
us-east-1 - TranscribeVocabularyFilter - [LanguageCode: "en-US", LastModifiedTime: "2023-09-05T14:33:02Z", Name: "test-vocab-filter-a3b39174b6ba8c8f18f9"] - removed
us-east-1 - TranscribeVocabularyFilter - [LanguageCode: "en-US", LastModifiedTime: "2023-09-06T14:29:20Z", Name: "test-vocab-filter-9f05901a7d6ab64ac886"] - removed
us-east-1 - TranscribeLanguageModel - [BaseModelName: "NarrowBand", CreateTime: "2023-09-06T14:29:00Z", LanguageCode: "en-US", LastModifiedTime: "2023-09-06T14:29:09Z", ModelStatus: "IN_PROGRESS", Name: "my-first-language-model-9f05901a7d6ab64ac886", UpgradeAvailability: "false"] - failed
us-east-1 - TranscribeLanguageModel - [BaseModelName: "NarrowBand", CreateTime: "2023-09-05T14:32:49Z", FailureReason: "You can't create a custom language model by only using this training data. Either specify additional tuning data or use multiple text files to provide your training data.", LanguageCode: "en-US", LastModifiedTime: "2023-09-05T15:10:39Z", ModelStatus: "FAILED", Name: "my-first-language-model-a3b39174b6ba8c8f18f9", UpgradeAvailability: "false"] - removed
us-east-1 - TranscribeMedicalTranscriptionJob - [CreationTime: "2023-09-06T14:29:08Z", FailureReason: "The audio sample rate 8000 Hz is not supported. Change the audio sample rate of your media file and try your request again.", InputType: "DICTATION", LanguageCode: "en-US", Name: "test-med-job-9f05901a7d6ab64ac886", OutputLocationType: "CUSTOMER_BUCKET", Specialty: "PRIMARYCARE", StartTime: "2023-09-06T14:29:09Z", Status: "FAILED"] - removed
us-east-1 - TranscribeMedicalTranscriptionJob - [CreationTime: "2023-09-05T14:32:56Z", FailureReason: "The audio sample rate 8000 Hz is not supported. Change the audio sample rate of your media file and try your request again.", InputType: "DICTATION", LanguageCode: "en-US", Name: "test-med-job-a3b39174b6ba8c8f18f9", OutputLocationType: "CUSTOMER_BUCKET", Specialty: "PRIMARYCARE", StartTime: "2023-09-05T14:32:56Z", Status: "FAILED"] - removed
us-east-1 - TranscribeCallAnalyticsJob - [CompletionTime: "2023-09-06T14:30:09Z", CreationTime: "2023-09-06T14:28:56Z", LanguageCode: "en-US", Name: "test-job-9f05901a7d6ab64ac886", StartTime: "2023-09-06T14:28:56Z", Status: "COMPLETED"] - removed
us-east-1 - TranscribeCallAnalyticsJob - [CompletionTime: "2023-09-05T14:34:00Z", CreationTime: "2023-09-05T14:32:47Z", LanguageCode: "en-US", Name: "test-job-a3b39174b6ba8c8f18f9", StartTime: "2023-09-05T14:32:47Z", Status: "COMPLETED"] - removed
us-east-1 - TranscribeTranscriptionJob - [CompletionTime: "2023-09-06T14:29:25Z", CreationTime: "2023-09-06T14:29:15Z", LanguageCode: "en-US", Name: "test-job-9f05901a7d6ab64ac886", StartTime: "2023-09-06T14:29:15Z", Status: "COMPLETED"] - removed
us-east-1 - TranscribeTranscriptionJob - [CompletionTime: "2023-09-05T14:33:10Z", CreationTime: "2023-09-05T14:33:00Z", LanguageCode: "en-US", Name: "test-job-a3b39174b6ba8c8f18f9", StartTime: "2023-09-05T14:33:00Z", Status: "COMPLETED"] - removed
us-east-1 - TranscribeCallAnalyticsCategory - [CreateTime: "2023-09-06T14:28:48Z", InputType: "POST_CALL", LastUpdateTime: "2023-09-06T14:28:48Z", Name: "test-category-9f05901a7d6ab64ac886"] - removed
us-east-1 - TranscribeCallAnalyticsCategory - [CreateTime: "2023-09-05T14:32:35Z", InputType: "POST_CALL", LastUpdateTime: "2023-09-05T14:32:35Z", Name: "test-category-a3b39174b6ba8c8f18f9"] - removed

Removal requested: 0 waiting, 1 failed, 0 skipped, 15 finished
```

Followed up after the model training failed.
```
Removal requested: 1 waiting, 0 failed, 0 skipped, 0 finished

us-east-1 - TranscribeLanguageModel - [BaseModelName: "NarrowBand", CreateTime: "2023-09-06T14:29:00Z", FailureReason: "You can't create a custom language model by only using this training data. Either specify additional tuning data or use multiple text files to provide your training data.", LanguageCode: "en-US", LastModifiedTime: "2023-09-06T15:03:36Z", ModelStatus: "FAILED", Name: "my-first-language-model-9f05901a7d6ab64ac886", UpgradeAvailability: "false"] - waiting

Removal requested: 1 waiting, 0 failed, 0 skipped, 0 finished

us-east-1 - TranscribeLanguageModel - [BaseModelName: "NarrowBand", CreateTime: "2023-09-06T14:29:00Z", FailureReason: "You can't create a custom language model by only using this training data. Either specify additional tuning data or use multiple text files to provide your training data.", LanguageCode: "en-US", LastModifiedTime: "2023-09-06T15:03:36Z", ModelStatus: "FAILED", Name: "my-first-language-model-9f05901a7d6ab64ac886", UpgradeAvailability: "false"] - removed

Removal requested: 0 waiting, 0 failed, 0 skipped, 1 finished

Nuke complete: 0 failed, 0 skipped, 1 finished.
```

**Review by swhite-oreilly — APPROVED** [review]

**Pull request merged**
