### PR TITLE
Updating detection filters.

### PR DESCRIPTION
**Pull request by swhite-oreilly**
### Description
Adding `Completed` to the job status types that are ignored upon cleanup for all Comprehend job types.

Adding support for the following job types: `ComprehendEventsDetectionJob`, `ComprehendPiiEntititesDetectionJob`, and `ComprehendTargetedSentimentDetectionJob`.  

### Note
`document-classification-job` and `topics-detection-job` do not have stop functions in the CLI nor Boto3.  As any personal identifying data is deleted on S3 cleanup, and these jobs technically don't store anything but metadata links to the files in S3 and naming/tags, the team has decided support for these can be left in and it isn't a hard requirement to add support for these at this time.

### CODE REVIEW

**Review by gsoria — COMMENTED** [review]
These changes make sense to me. I've tried it locally and I see that the completed SentimentDetectionJob and EntitiesDetectionJob jobs were skipped.

**main**

```
us-east-1 - ComprehendEntityRecognizer - arn:aws:comprehend:us-east-1:318480998194:entity-recognizer/test-3241623422e062a1c5f9b9199432bff80d4109be - [EntityRecognizerArn: "arn:aws:comprehend:us-east-1:318480998194:entity-recognizer/test-3241623422e062a1c5f9b9199432bff80d4109be", LanguageCode: "en"] - would remove
us-east-1 - ComprehendDocumentClassifier - arn:aws:comprehend:us-east-1:318480998194:document-classifier/testDelete-3241623422e062a1c5f9b9199432bff80d4109be - [DocumentClassifierArn: "arn:aws:comprehend:us-east-1:318480998194:document-classifier/testDelete-3241623422e062a1c5f9b9199432bff80d4109be", LanguageCode: "en"] - would remove
us-east-1 - ComprehendSentimentDetectionJob - sentiment-analysis-3241623422e062a1c5f9b9199432bff80d4109be - [JobId: "c08aabeafd134afef71126260046ada6", JobName: "sentiment-analysis-3241623422e062a1c5f9b9199432bff80d4109be"] - would remove
us-east-1 - ComprehendEntitiesDetectionJob - entities-analysis-3241623422e062a1c5f9b9199432bff80d4109be - [JobId: "d7f4050116539b3ac90baf530c22807e", JobName: "entities-analysis-3241623422e062a1c5f9b9199432bff80d4109be"] - would remove
Scan complete: 4 total, 4 nukeable, 0 filtered.
```

**this branch**

```
us-east-1 - ComprehendEntityRecognizer - arn:aws:comprehend:us-east-1:318480998194:entity-recognizer/test-3241623422e062a1c5f9b9199432bff80d4109be - [EntityRecognizerArn: "arn:aws:comprehend:us-east-1:318480998194:entity-recognizer/test-3241623422e062a1c5f9b9199432bff80d4109be", LanguageCode: "en"] - would remove
us-east-1 - ComprehendDocumentClassifier - arn:aws:comprehend:us-east-1:318480998194:document-classifier/testDelete-3241623422e062a1c5f9b9199432bff80d4109be - [DocumentClassifierArn: "arn:aws:comprehend:us-east-1:318480998194:document-classifier/testDelete-3241623422e062a1c5f9b9199432bff80d4109be", LanguageCode: "en"] - would remove
Scan complete: 2 total, 2 nukeable, 0 filtered.
```

I see there are other resources not supported by aws-nuke nor cloud control API:
- document-classification-job
- document-classifier-endpoint
- entity-recognizer-endpoint
- events-detection-job
- pii-entities-detection-job
- targeted-sentiment-detection-job
- topics-detection-job

Are these going to be covered as part of your changes?

**Review by corybekk — APPROVED** [review]
Just to make sure I am understanding the change, aws-nuke was trying to delete resources that were in the "completed" state? i.e resources that have already been deleted?

**Comment by swhite-oreilly** [comment]
> Just to make sure I am understanding the change, aws-nuke was trying to delete resources that were in the "completed" state? i.e resources that have already been deleted?

@corybekk These don't actually get deleted as they are just metadata pointing to the trained files in S3.  The original function goal was to stop in progress jobs, but they missed filtering out those in the `Completed` status so they were causing errors because they were in the wrong state.

**Comment by swhite-oreilly** [comment]
> These changes make sense to me. I've tried it locally and I see that the completed SentimentDetectionJob and EntitiesDetectionJob jobs were skipped.
> 
> **main**
> 
> ```
> us-east-1 - ComprehendEntityRecognizer - arn:aws:comprehend:us-east-1:318480998194:entity-recognizer/test-3241623422e062a1c5f9b9199432bff80d4109be - [EntityRecognizerArn: "arn:aws:comprehend:us-east-1:318480998194:entity-recognizer/test-3241623422e062a1c5f9b9199432bff80d4109be", LanguageCode: "en"] - would remove
> us-east-1 - ComprehendDocumentClassifier - arn:aws:comprehend:us-east-1:318480998194:document-classifier/testDelete-3241623422e062a1c5f9b9199432bff80d4109be - [DocumentClassifierArn: "arn:aws:comprehend:us-east-1:318480998194:document-classifier/testDelete-3241623422e062a1c5f9b9199432bff80d4109be", LanguageCode: "en"] - would remove
> us-east-1 - ComprehendSentimentDetectionJob - sentiment-analysis-3241623422e062a1c5f9b9199432bff80d4109be - [JobId: "c08aabeafd134afef71126260046ada6", JobName: "sentiment-analysis-3241623422e062a1c5f9b9199432bff80d4109be"] - would remove
> us-east-1 - ComprehendEntitiesDetectionJob - entities-analysis-3241623422e062a1c5f9b9199432bff80d4109be - [JobId: "d7f4050116539b3ac90baf530c22807e", JobName: "entities-analysis-3241623422e062a1c5f9b9199432bff80d4109be"] - would remove
> Scan complete: 4 total, 4 nukeable, 0 filtered.
> ```
> 
> **this branch**
> 
> ```
> us-east-1 - ComprehendEntityRecognizer - arn:aws:comprehend:us-east-1:318480998194:entity-recognizer/test-3241623422e062a1c5f9b9199432bff80d4109be - [EntityRecognizerArn: "arn:aws:comprehend:us-east-1:318480998194:entity-recognizer/test-3241623422e062a1c5f9b9199432bff80d4109be", LanguageCode: "en"] - would remove
> us-east-1 - ComprehendDocumentClassifier - arn:aws:comprehend:us-east-1:318480998194:document-classifier/testDelete-3241623422e062a1c5f9b9199432bff80d4109be - [DocumentClassifierArn: "arn:aws:comprehend:us-east-1:318480998194:document-classifier/testDelete-3241623422e062a1c5f9b9199432bff80d4109be", LanguageCode: "en"] - would remove
> Scan complete: 2 total, 2 nukeable, 0 filtered.
> ```
> 
> I see there are other resources not supported by aws-nuke nor cloud control API:
> 
>     * document-classification-job
> 
>     * document-classifier-endpoint
> 
>     * entity-recognizer-endpoint
> 
>     * events-detection-job
> 
>     * pii-entities-detection-job
> 
>     * targeted-sentiment-detection-job
> 
>     * topics-detection-job
> 
> 
> Are these going to be covered as part of your changes?

@gsoria retesting these now and will follow up probably with a separate PR adding support.

**Comment by corybekk** [comment]
> > Just to make sure I am understanding the change, aws-nuke was trying to delete resources that were in the "completed" state? i.e resources that have already been deleted?
> 
> @corybekk These don't actually get deleted as they are just metadata pointing to the trained files in S3. The original function goal was to stop in progress jobs, but they missed filtering out those in the `Completed` status so they were causing errors because they were in the wrong state.

thanks for the clarification!

**Pull request merged**
